In [1]:

 pip install climate-indices

Requirement already satisfied: climate-indices in c:\users\parat\anaconda3\lib\site-packages (2.0.0)
Requirement already satisfied: cftime==1.6.2 in c:\users\parat\anaconda3\lib\site-packages (from climate-indices) (1.6.2)
Requirement already satisfied: xarray==2023.1.0 in c:\users\parat\anaconda3\lib\site-packages (from climate-indices) (2023.1.0)
Requirement already satisfied: h5netcdf==1.1.0 in c:\users\parat\anaconda3\lib\site-packages (from climate-indices) (1.1.0)
Requirement already satisfied: scipy==1.9.3 in c:\users\parat\anaconda3\lib\site-packages (from climate-indices) (1.9.3)
Requirement already satisfied: dask==2022.2.0 in c:\users\parat\anaconda3\lib\site-packages (from climate-indices) (2022.2.0)
Requirement already satisfied: numpy>1.13.3 in c:\users\parat\anaconda3\lib\site-packages (from cftime==1.6.2->climate-indices) (1.21.5)
Requirement already satisfied: partd>=0.3.10 in c:\users\parat\anaconda3\lib\site-packages (from dask==2022.2.0->climate-indices) (1.2.0)
Requirement already satisfied: cloudpickle>=1.1.1 in c:\users\parat\anaconda3\lib\site-packages (from dask==2022.2.0->climate-indices) (2.0.0)
Requirement already satisfied: fsspec>=0.6.0 in c:\users\parat\anaconda3\lib\site-packages (from dask==2022.2.0->climate-indices) (2022.7.1)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\parat\anaconda3\lib\site-packages (from dask==2022.2.0->climate-indices) (6.0)
Requirement already satisfied: packaging>=20.0 in c:\users\parat\anaconda3\lib\site-packages (from dask==2022.2.0->climate-indices) (21.3)
Requirement already satisfied: toolz>=0.8.2 in c:\users\parat\anaconda3\lib\site-packages (from dask==2022.2.0->climate-indices) (0.11.2)
Requirement already satisfied: h5py in c:\users\parat\anaconda3\lib\site-packages (from h5netcdf==1.1.0->climate-indices) (3.7.0)
Requirement already satisfied: pandas>=1.3 in c:\users\parat\anaconda3\lib\site-packages (from xarray==2023.1.0->climate-indices) (1.4.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\parat\anaconda3\lib\site-packages (from packaging>=20.0->dask==2022.2.0->climate-indices) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in c:\users\parat\anaconda3\lib\site-packages (from pandas>=1.3->xarray==2023.1.0->climate-indices) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\parat\anaconda3\lib\site-packages (from pandas>=1.3->xarray==2023.1.0->climate-indices) (2.8.2)
Requirement already satisfied: locket in c:\users\parat\anaconda3\lib\site-packages (from partd>=0.3.10->dask==2022.2.0->climate-indices) (1.0.0)
Requirement already satisfied: six>=1.5 in c:\users\parat\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.3->xarray==2023.1.0->climate-indices) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
from scipy.stats import rankdata
import pandas as pd
from climate_indices import compute
import matplotlib.pyplot as plt

In [3]:
pip install ruptures

Requirement already satisfied: ruptures in c:\users\parat\anaconda3\lib\site-packages (1.1.9)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: scipy in c:\users\parat\anaconda3\lib\site-packages (from ruptures) (1.9.3)
Requirement already satisfied: numpy in c:\users\parat\anaconda3\lib\site-packages (from ruptures) (1.21.5)

In [9]:

file_path = 'India_Interpolated_Rainy_Days_RW.xlsx'
df = pd.read_excel(file_path)
df1=pd.read_excel('d1.xlsx')
df2=pd.read_excel('d2.xlsx')

In [10]:
del df['State']
del df['Area']
del df['Longitude']
del df['Latitude']
del df['fid']
del df['Altitude']

In [11]:
df

,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,84,78,85,98,80,96,101,103,112,96,...,102,91,120,72,114,91,103,108,128,122
1,84,78,85,99,80,97,102,103,112,96,...,102,91,119,72,113,90,103,108,128,121
2,93,78,89,98,82,98,103,105,113,100,...,99,89,118,76,114,89,102,109,126,119
3,98,75,83,76,72,84,71,87,89,86,...,103,81,111,67,89,67,86,109,113,106
4,86,70,84,51,89,85,74,89,92,88,...,117,102,123,87,112,88,110,122,137,130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,73,57,63,80,80,72,73,66,82,67,...,102,66,98,59,76,53,77,90,98,92
1359,79,77,83,105,84,95,92,94,85,88,...,110,101,130,104,134,104,123,125,146,135
1360,95,81,96,103,87,113,110,106,116,110,...,100,88,111,73,110,82,103,109,120,118
1361,71,62,57,56,71,67,54,50,63,62,...,96,90,109,71,101,88,106,103,128,119
1362,86,77,90,91,83,86,77,88,87,93,...,100,90,122,87,125,99,102,113,121,126

In [12]:
def pettitt_test(x):
    n = len(x)
    rank = rankdata(x)
    U = np.zeros(n)

    for k in range(n):
        U[k] = 2 * np.sum(rank[:k+1]) - (k+1) * (n+1)
    
    U = np.abs(U)
    K = np.argmax(U)
    U_max = U[K]
    p_value = 2 * np.exp((-6 * U_max**2) / (n**3 + n**2))
    return K, p_value

In [13]:
change_points = []
p_values = []
for index, row in df.iterrows():
    data = row.values[1:]  
    K, p_value = pettitt_test(data)
    change_points.append(K)
    p_values.append(p_value)

# Add the results back to the DataFrame
df['Change_Point_Index'] = change_points
df['p_value'] = p_values

# Save the results back to the Excel file
df.to_excel('output_with_change_points.xlsx', index=False)

# Print the results for verification
print(df)

      1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  ...  2015  \
0       84    78    85    98    80    96   101   103   112    96  ...   120
1       84    78    85    99    80    97   102   103   112    96  ...   119
2       93    78    89    98    82    98   103   105   113   100  ...   118
3       98    75    83    76    72    84    71    87    89    86  ...   111
4       86    70    84    51    89    85    74    89    92    88  ...   123
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...
1358    73    57    63    80    80    72    73    66    82    67  ...    98
1359    79    77    83   105    84    95    92    94    85    88  ...   130
1360    95    81    96   103    87   113   110   106   116   110  ...   111
1361    71    62    57    56    71    67    54    50    63    62  ...   109
1362    86    77    90    91    83    86    77    88    87    93  ...   122

      2016  2017  2018  2019  2020  2021  2022  Change_Point_Index   p_value
0       72   114    91   103   108   128   122                  15  0.056720
1       72   113    90   103   108   128   121                  15  0.049347
2       76   114    89   102   109   126   119                  15  0.109325
3       67    89    67    86   109   113   106                  17  0.262670
4       87   112    88   110   122   137   130                  17  0.002247
...    ...   ...   ...   ...   ...   ...   ...                 ...       ...
1358    59    76    53    77    90    98    92                  14  0.037054
1359   104   134   104   123   125   146   135                  17  0.000089
1360    73   110    82   103   109   120   118                  15  0.440605
1361    71   101    88   106   103   128   119                  14  0.000051
1362    87   125    99   102   113   121   126                  14  0.000595

[1363 rows x 37 columns]

In [14]:
df

,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,...,2015,2016,2017,2018,2019,2020,2021,2022,Change_Point_Index,p_value
0,84,78,85,98,80,96,101,103,112,96,...,120,72,114,91,103,108,128,122,15,0.056720
1,84,78,85,99,80,97,102,103,112,96,...,119,72,113,90,103,108,128,121,15,0.049347
2,93,78,89,98,82,98,103,105,113,100,...,118,76,114,89,102,109,126,119,15,0.109325
3,98,75,83,76,72,84,71,87,89,86,...,111,67,89,67,86,109,113,106,17,0.262670
4,86,70,84,51,89,85,74,89,92,88,...,123,87,112,88,110,122,137,130,17,0.002247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,73,57,63,80,80,72,73,66,82,67,...,98,59,76,53,77,90,98,92,14,0.037054
1359,79,77,83,105,84,95,92,94,85,88,...,130,104,134,104,123,125,146,135,17,0.000089
1360,95,81,96,103,87,113,110,106,116,110,...,111,73,110,82,103,109,120,118,15,0.440605
1361,71,62,57,56,71,67,54,50,63,62,...,109,71,101,88,106,103,128,119,14,0.000051
1362,86,77,90,91,83,86,77,88,87,93,...,122,87,125,99,102,113,121,126,14,0.000595